### PR TITLE
feat: export driver

### PR DESCRIPTION
**Pull request by chenquan**

### CODE REVIEW

**Comment by sangshuduo** [comment]
@chenquan hello, may I know why you need to export driver to visible?

**Comment by chenquan** [comment]
> @chenquan hello, may I know why you need to export driver to visible?

 I want to be able to export drivers to enhance their capabilities, for example, using the [sqlplus](https://github.com/chenquan/sqlplus) library.

**Comment by huskar-t** [comment]
I don't think it is safe and wise to expose it.

**Comment by chenquan** [comment]
I don't think exposing it would present any security problems at this time.
cases:
- https://github.com/go-sql-driver/mysql
- https://github.com/mattn/go-sqlite3

**Comment by chenquan** [comment]
https://github.com/taosdata/driver-go/blob/5c3eda628f1f1ba87404c2be25ef9a2879b487cc/taosSql/driver.go#L19
Indicate in the comment that it has been exported. :sob:

**Review by huskar-t — CHANGES_REQUESTED** [review]
change `TdengineDriver` to `TDengineDriver`

**Comment by chenquan** [comment]
> change `TdengineDriver` to `TDengineDriver`

done.

**Review by huskar-t — APPROVED** [review]
LGTM

**Comment by chenquan** [comment]
@huskar-t Hello, when can you release a  new version?

**Pull request merged**
